-- CREATE DATABASE TESTE;
-- SHOW DATABASES;

-- SELECT * FROM usuarios;
-- DELETE FROM usuarios WHERE NOME = "";

-- USE mysql;
-- SHOW TABLES;

CREATE DATABASE IF NOT EXISTS aula;
DROP TABLE IF EXISTS pessoa; 
SHOW DATABASES;
USE aula;
CREATE TABLE Pessoa(
	cpf CHAR(11) PRIMARY KEY,
	nome VARCHAR(100)
);

SHOW TABLES;